shazow/whatsabi

src.ts/loaders.ts
The metadata file contains the abi under `outputs.abi` and that should be returned instead of the full metadata file.
=> Fix getting ABI from Sourcify metadata

src.ts/opcodes.ts
small issue i hit when using `isSwap` because of an undefined field
=> fix isSwap

.gitignore, .size-limit.js, Makefile, package-lock.json, package.json, src/__tests__/env.ts, src/__tests__/index.test.ts, src/__tests__/util.test.ts, src/auto.ts, src/disasm.ts, src/internal/debug.ts, src/loaders.ts, src/proxies.ts, src/selectors.ts, src/types.ts, src/utils.ts, tsconfig.base.json, tsconfig.cjs.json, tsconfig.esm.json, tsconfig.json, tsconfig.types.json
Re #46 
- Switched from ethers 5 to ethers 6 with better tree-shaking, only using the abi parsing sub-module
- Implement our own hex/byte conversion and keccak wrapper
- Use noble as a peer-dependency from ethers 6
- Overall reduced bundle size from 144 KB to 12 KB!!!❗❗❗
=> Become provider agnostic, reduce bundle size

src/__tests__/auto.test.ts, src/__tests__/examples.test.ts, src/__tests__/loaders.test.ts, src/abi.ts, src/auto.ts, src/disasm.ts, vite.config.ts
- autoload: Test EOA, fix viem handling
- disasm: Include empty name fields for inputs and outputs
=> Fix autoload EOA handling for viem; include empty name fields

src/loaders.ts
Completes #72 
Not sure your standard, but didn't want to make the function param an object as it would introduce a breaking change.
=> Add a baseURL param to defaultsWithAPIKeys

src/__tests__/loaders.test.ts, src/loaders.ts
Types for EvmVersion and ContractData (return value for getContract)
Implementation for Etherscan + Sourcify getContract()
=> feat: getContract

README.md, src/loaders.ts
Made `ContractResult` non-nullable (and renamed to be similar to `AutoloadResult`).
This way we can do more ergonomic
```typescript
const { abi, name, ok } = await loader.getContract(address);
if (!ok) throw "failed"; // If we care, or skip this altogether if we don't
...
```
Rather than
```typescript
const result = await loader.getContract(address);
if (result === null) throw "failed"; // Need this check either way, because it's nullable
const { abi, name } = result;
...
```
@SonOfMosiah what do you think?
=> loaders: getContract returns non-nullable ContractResult

src/types.ts
Quick fix to make whatsabi compatible with the latest version of the viem public client. Ideally this should not rely on a deprecated function being present but for example on the "type" property of the provider being equal to "publicClient" (or anything else that can be used to difference providers).
Fixes issue #93
=> switch viem and ethersv5 provider order

README.md, src/__tests__/auto.test.ts, src/__tests__/env.ts, src/__tests__/examples.test.ts, src/auto.ts, src/providers.ts
- Reformatted some tests, ignore whitespace plz
- Added explicit viem example to the README, so it's more clear that whatsabi is not ethers-only (fixes #106)
- Added AutoloadError wrapper for when provider does not support ENS with instructions to specify addressResolver
- Added test for passing in a fake provider without ENS support
- Refactored the provider abstraction to be a bit more EIP-1193-centric.
- Default viem test suite now runs with a `createWalletClient` instead of a `createPublicClient`
- Fixes #105 ?
Obsoletes #104
=> providers: Fix viem non-public clients, wrap autoload ENS error

Makefile, README.md, src/__tests__/examples.test.ts, src/__tests__/loaders.test.ts, src/loaders.ts
- Added `getSources?: () => Promise<ContractSources>;` to `ContractResult`
- Currently only supported by the Etherscan loader
- `ContractSources` automatically deserializes the encoded source code structure. This will help once we add support for the Sourcify loader which uses a different format (and will require a separate request for each import).
- `ContractResult` is not yet accessible from `AutoloadResult`, so would need to use loaders directly to access it for now. (This will require a bit more plumbing, since autoload uses loadABI rather than loadContract, so we'll need yet another flag to include contract sources.)
- Fixes #111 
Usage:
```typescript
const result = await loader.getContract(address);
const sources = await result.getSources();
for (const s of sources) { …
```
=> loaders: Add getSources() to ContractResult

src/__tests__/auto.test.ts, src/__tests__/env.ts, src/auto.ts
Example:
```typescript
// USDT, available on both PulseChain and Mainnet (but only verified on mainnet)
const address = "0xdAC17F958D2ee523a2206206994597C13D831ec7";
const result = await autoload(address, {
provider: pulseChainProvider,
crossChainLoad: {
mainnnetProvider,
...whatsabi.loaders.defaultsWithEnv(env),
}
});
console.log(result); // {isVerified: true, abi: [...], ...}
```
=> auto: Add CrossChainLoad support for verified contracts

src/__tests__/loaders.test.ts, src/loaders.ts
Resolves #117 
Add fallback in the `SourcifyABILoader` to handle cases where the contract name is missing from the Natspec comments (`devdoc.title`).
=> src/loader.ts: Add fallback for contract name in SourcifyABILoader

src/__tests__/loaders.test.ts, src/loaders.ts
- Add `ContractResult.loaderResult?: any`
- Remove `userdoc` and `devdoc` added earlier, should be accessed via `loaderResult` now.
- Updated tests
- Added test for Compound USDCv3 TransparentProxy resolving via Etherscan. We still need to fix our own proxy resolving for this one.
- Resolves #125
=> loaders: Add loaderResult, remove {userdoc,devdoc}

src/loaders.ts
Follow-up PR to #127
**Change overview**
- Introduced `EtherscanContractResult` type
- Introduced `SourcifyContractMetadata` type
- Updated `ContractResult.loaderResult` type
=> loaders: Enhance `ContractResult.loaderResult` type

src/__tests__/auto.test.ts, src/auto.ts, src/proxies.ts
=> autoload: AutoloadResult.ContractResult

src/auto.ts
This PR updates the autoload function to improve handling of unverified contracts. If a contract's ABI is empty, we now fallback to using the inferred ABI instead of returning empty ABI.
Please see:
- #136
**Note:** The problem only occurs when `loadContractResult: true` is set in `AutoloadConfig`
=> src/auto.ts: check if contractResult.abi is not empty

src/loaders.ts
Hi @shazow,
I made a small adjustment. This fix is necessary because, in MultiABILoader, when an exception occurs in the Etherscan loader, it does not fall back to the Sourcify loader (when they are set in MultiABILoader in this order). I would appreciate it if you could kindly review it.
Example response from Etherscan API:
=> loaders: Avoid exception when Etherscan returns an empty response

src/__tests__/auto.test.ts, src/auto.ts, src/disasm.ts
Adds `AutoloadResult.isFactory` property for when a CREATE/CREATE2 opcode is present.
Will be useful for end-users to distinguish some proxy scenarios. (e.g. #142)
=> autoload: Add AutoloadResult.isFactory

src/auto.ts
if `prepare: false`, then the value won't contain the signature hash (and will consequently perform better as it won't perform a keccak256 call).
=> chore: prepare = false

README.md, src/__tests__/loaders.test.ts, src/loaders.ts
Resolves issue #149
**Overview**
This PR implements the `BlockscoutABILoader` to enable loading ABIs from Blockscout's API.
**To do**
=> loaders: Add Blockscout ABI support

src/__tests__/env.ts, src/__tests__/loaders.test.ts, src/loaders.ts
Preparing to add more loaders.
- Add test suite for loaders in general
- loaders.BlockscoutABILoader.loadABI updated to return [] on empty instead of throwing an error.
=> tests: Improve loader tests, add no-result checks

src/__tests__/loaders.test.ts, src/auto.ts, src/loaders.ts
Includes #156 #158 #160
Doing final tweaks and integration.
=> Add loaders: AnyABI, Etherscan v2

examples/autoload.ts, src/__tests__/auto.test.ts, src/auto.ts, src/disasm.ts
Fixes #173 
Summary: Sometimes a contract contains proxy-like code, but it's actually a destination contract itself.
This PR adds a heuristic where we skip the `AutoloadResult.followProxies` when the bytecode contains more than 4 SSTORE instructions.
I sampled a bunch of proxies, and most upgradeable proxies have 1-2 sstores, and typical contracts have dozens of sstores. 3 felt a little tight, but 5 feels pretty safe. Can tweak this later.
=> proxies: Skip followProxies if contract is complex enough to be a destination itself

README.md, src/loaders.ts
Etherscan v1 apis have been deprecated causing errors like below
```
MultiABILoader loadABI error: EtherscanABILoader loadABI error: Max calls per sec rate limit reached (2/sec). Please switch to API V2, for more info https://docs.etherscan.io/etherscan-v2/v2-quickstart
```
=> Upgrade to etherscan v2

README.md, src/__tests__/auto.test.ts, src/__tests__/examples.test.ts, src/__tests__/loaders.test.ts, src/loaders.ts
We use Etherscan V2 by default, no longer need a separate base URL for each non-mainnet chain.
```diff
...whatsabi.loaders.defaultsWithEnv({
-                SOURCIFY_CHAIN_ID: 42161,
-                ETHERSCAN_BASE_URL: "https://api.arbiscan.io/api",
+                CHAIN_ID: 42161,
ETHERSCAN_API_KEY: "MYSECRETAPIKEY",
}),
```
=> loaders: Use EtherscanV2ABILoader, add env.CHAIN_ID
