shazow/whatsabi

package-lock.json, package.json, src.ts/__tests__/auto.test.ts, src.ts/__tests__/index.test.ts, src.ts/auto.ts, src.ts/disasm.ts, src.ts/loaders.ts, src.ts/selectors.ts
Given an address, try All The Things to load an ABI.
=> WIP: autoload

.github/workflows/test.yml, src.ts/__tests__/auto.test.ts, src.ts/auto.ts, src.ts/bin/autoload.ts, src.ts/loaders.ts
Fixes #34 for now, can do more later.
=> autoload: Add hooks, enableExperimentalMetadata option, better error handling

src.ts/auto.ts, src.ts/proxies.ts, src.ts/types.ts
Related to: https://github.com/shazow/whatsabi/issues/11#issuecomment-1670259179
=> proxies, autoload: Implementation-agnostic provider

src/__tests__/proxies.test.ts, src/proxies.ts
Added more tests, fixed revert result detection. Fixes #53.
=> Improve proxy detection

src/loaders.ts
Would be great if we could modify the chain id for sourcify!
=> feat: add `chainId` to sourcify loader

src/loaders.ts
=> loaders.defaultsWithEnv

.env.example, README.md
=> README, .env.example: Add env example

examples/autoload.ts, src/__tests__/edges.test.ts, src/disasm.ts
=> disasm: Detect inverted selector jump condition (with fallback)

.github/workflows/test.yml, package.json, pnpm-lock.yaml, src/__tests__/env.ts, src/types.ts
=> Improve provider abstraction: Use low level RPC whenever possible

README.md
=> Add svvy.sh to readme

.github/workflows/docs.yml, .gitignore, Makefile, flake.lock, flake.nix, package.json, pnpm-lock.yaml, src/auto.ts, src/loaders.ts, src/whatsabi.ts, typedoc.json
=> Add generated docs

src/__tests__/auto.test.ts, src/__tests__/loaders.test.ts, src/auto.ts, src/loaders.ts
=> loaders: Add AutoloadResult.abiLoadedFrom and plumb the result through MultiABILoader

src/__tests__/providers.test.ts, src/providers.ts
=> providers: WithCachedCode should accept AnyProvider and make it compatible

src/providers.ts
=> src/providers.ts: WithCachedCode, include prototype chain of Provider

src/__tests__/auto.test.ts, src/__tests__/loaders.test.ts, src/__tests__/proxies.test.ts, src/__tests__/util.test.ts, src/disasm.ts
=> disasm: Handle padded resolved address for FixedProxyResolver

examples/resolveproxy.ts, src/__tests__/proxies.test.ts, src/disasm.ts
=> Handle multiple detected FixedProxyResolver better

examples/bytecode.ts, src/__tests__/proxies.test.ts, src/disasm.ts, src/internal/debug.ts, src/opcodes.ts
=> disasm: Detect code boundary and look for slots in aux data

src/__tests__/edges.test.ts, src/disasm.ts
=> src/disasm.ts: Use Set for eventCandidates to avoid dupes

package.json, pnpm-lock.yaml, src/__tests__/auto.test.ts, src/auto.ts, src/selectors.ts
=> ethers.js -> ox

src/__tests__/env.ts, src/__tests__/proxies.test.ts, src/proxies.ts
Add facet tests to comprehensive test suite
Closes https://github.com/shazow/whatsabi/pull/181
=> proxies: DiamondProxy should override off-by-one DIAMOND_STORAGE slot too
